_target_: cogelot.environment.VIMAEnvironment.from_config
seed: ${seed}
# We're just giving it any task here, it will get changed during the steps
task: 1
partition: 1
should_display_debug_window: true
should_render_prompt: true
should_hide_arm_rgb: true
record_gui: false
